# Generated by Django 4.2 on 2023-04-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(max_length=100)),
                ('studio', models.CharField()),
                ('time_class', models.TimeField()),
                ('date_class', models.DateField()),
                ('duration_class', models.CharField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cali', to='instructor.instructor')),
            ],
        ),
    ]
