# Generated by Django 4.2 on 2023-04-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('cali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cali',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='cali.cali'),
        ),
    ]
